### ISSUE TITLE
Update Methods

### ISSUE THREAD

**Issue by amyerspigg** [river-corridors-sfa/rc_sfa-rc-3-wenas-modeling#18]
Update to include when fire was started in the simulation: https://docs.google.com/document/d/1q9dt2cGy9OSUBsxmJ-qIWM8JGNJaFRsm-HKY4pgcgWc/edit

**Comment by katiewampler** [comment]
updated, also updated the method for choosing burned HRU's and the number of subbasins/HRU's in the new model
