### ISSUE TITLE
Need correct fire start date?

### ISSUE THREAD

**Issue by amyerspigg** [river-corridors-sfa/rc_sfa-rc-3-wenas-modeling#19]
https://github.com/river-corridors-sfa/rc_sfa-rc-3-wenas-modeling/blob/bba0b662391b486d5699d7344f8c5692e63e29e6/230718_create_L1_dataset.Rmd#L143

I am pretty sure this is the wrong date. according to emails with Katie: 

fire_start = as.POSIXct("2019-08-31") # model fire started in 2019 #

**Comment by amyerspigg** [comment]
Evan's Canyon Fire Info: 

https://inciweb.nwcg.gov/incident-information/wases-evans-canyon-fire

https://www.wsp.wa.gov/2020/09/01/state-fire-mobilization-authorized-for-the-evans-canyon-fire/

**Comment by peterregier** [comment]
I went for 365 days to have a single year. Do we want to start 8/31 and calculate stats on 15 months instead of a consistent calendar year?

**Comment by amyerspigg** [comment]
just saw this. I think we want 8/31- 8/31

**Comment by amyerspigg** [comment]
Updated start date but left for the 15th months, need to decide when to cut still.

**Comment by amyerspigg** [comment]
new issue c reated with new end date

**Comment by peterregier** [comment]
Documenting: there are several days where there is no flow, so the model could not produce DOC/NO3/etc. Those days are left in to keep the dataset whole, and can be removed in subsequent analyses
