### ISSUE TITLE
100% is showing as 10%

### ISSUE THREAD

**Issue by amyerspigg** [river-corridors-sfa/rc_sfa-rc-3-wenas-modeling#22]
https://github.com/river-corridors-sfa/rc_sfa-rc-3-wenas-modeling/blob/c4ced5f6a6bc1027e773ab722e4418f66bef29d6/230718_create_L1_dataset.Rmd#L114

**Comment by amyerspigg** [comment]
Tried mutate differently with a different stringr and resolved

**Comment by peterregier** [comment]
Thx for fixing, plots confirm this is fixed
