### ISSUE TITLE
Missing scenarios and I dont know why...

### ISSUE THREAD

**Issue by amyerspigg** [river-corridors-sfa/rc_sfa-rc-3-wenas-modeling#23]
https://github.com/river-corridors-sfa/rc_sfa-rc-3-wenas-modeling/blob/ab4eab266b4e9071dd11c682a6476928d5625974/230718_create_L1_dataset.Rmd#L114-L119

Missing 10_MOD, 10_LOW, 100_MOD, 15_MOD, 20_HIGH, 45_LOW, 50_MOD, 50_HIGH, 90_MOD...

**Comment by peterregier** [comment]
Agreed, thx for fixing! All scenarios show up for flow, sed, no3, and doc based on plotting
