### ISSUE TITLE
Create Prelim Graphics for Scenarios

### ISSUE THREAD

**Issue by amyerspigg** [river-corridors-sfa/rc_sfa-rc-3-wenas-modeling#3]
Using old model outputs 

- [x] % area burn x fire severity vs base case (bar charts) Mean values 
- [x] All other scenarios vs base case (bar charts) Mean Values

**Comment by amyerspigg** [comment]
https://github.com/river-corridors-sfa/rc_sfa-rc-3-wenas-modeling/blob/pregier/pr_work/figures/230330_fire_characteristics_bar_charts.png

**Comment by peterregier** [comment]
https://github.com/river-corridors-sfa/rc_sfa-rc-3-wenas-modeling/blob/pregier/pr_work/figures/230410_scenario_percent_changes.png
