### ISSUE TITLE
Slope changes – percentages

### ISSUE THREAD

**Issue by amyerspigg** [river-corridors-sfa/rc_sfa-rc-3-wenas-modeling#9]
What are the units of slope in the Figure 3, and how is %change in slope defined?
For example, if slope was 100%, and the change was -100%, is the slope 0? What about if it was 50% and change was -100%?

**Comment by katiewampler** [comment]
I'm unsure of where to find Figure 3, but the units are m/m (rise over run). The perent change in slope is either a 10%, 50%, or 100% increase so slope*(1+0.1 or 0.5 or 1) or negative changes would be slope*(1-0.1 or 0.5 or 1). Does that help?

**Comment by amyerspigg** [comment]
Yep, this helps. Here is the figure we were referring to: https://drive.google.com/drive/folders/1GUSGpWNKvs0AY0wjlVLs-jkOKy3g-JqL

**Comment by amyerspigg** [comment]
If we decrease to -100% does that mean the slopes are then negative, or just 0?

**Comment by katiewampler** [comment]
decreasing by 100% means the slopes are just 0.
